### ISSUE TITLE
FbxExporter Wrapper

### ISSUE THREAD

**Issue by s4trace** [izrik/FbxSharp#38]
I noticed the FbxExporter wrapper class is missing from this project, unless I'm mistaken. Are there plans to include this in future commits?

**Comment by izrik** [comment]
@s4trace Maybe. I've heard rumors of Autodesk bringing legal action against that, so I'd want to make sure it's allowed first. But in principle there's no objection.

**Comment by HelloKitty** [comment]
Does the exporter exist now?

**Comment by izrik** [comment]
@HelloKitty Not at this time. Some other projects may support that functionality. For example, the Unity Game Engine has an exporter [here](https://docs.unity3d.com/Packages/com.unity.formats.fbx@3.0/manual/index.html), although I don't know if that's accessible from C# code.
